#!/bin/bash
# =============================================================================
# TurboFlow 4.0 — Container Entrypoint
#
# Runs lightweight first-boot tasks that can't be baked into the image
# (they depend on runtime state like API keys, git identity, mounted volumes).
# Subsequent starts skip completed steps via a done-flag.
# =============================================================================
set -uo pipefail

DONE_FLAG="$HOME/.turboflow-container-init-done"
ALIAS_FILE="$HOME/.turboflow_aliases"

# ── Always ensure PATH is correct ────────────────────────────────────────────
export PATH="$HOME/.npm-global/bin:$HOME/.local/bin:$HOME/.claude/bin:$PATH"
export CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1

# ── Source aliases if they exist ─────────────────────────────────────────────
[ -f "$ALIAS_FILE" ] && source "$ALIAS_FILE"

# ── First-boot initialization ────────────────────────────────────────────────
if [ ! -f "$DONE_FLAG" ]; then
    echo "╔══════════════════════════════════════════════════╗"
    echo "║     🚀 TurboFlow 4.0 — First Boot Setup         ║"
    echo "╚══════════════════════════════════════════════════╝"
    echo ""

    # 1. Sync Dolt identity with git config (if user mounted .gitconfig)
    if command -v dolt &>/dev/null; then
        GIT_NAME="$(git config --global user.name 2>/dev/null || echo 'TurboFlow Agent')"
        GIT_EMAIL="$(git config --global user.email 2>/dev/null || echo 'agent@turboflow.local')"
        dolt config --global --add user.name "$GIT_NAME" 2>/dev/null || true
        dolt config --global --add user.email "$GIT_EMAIL" 2>/dev/null || true
        echo "  ✓ Dolt identity: $GIT_NAME <$GIT_EMAIL>"
    fi

    # 2. Initialize Beads in workspace if .git exists and .beads doesn't
    if command -v bd &>/dev/null && command -v dolt &>/dev/null; then
        if [ -d "/workspace/.git" ] && [ ! -d "/workspace/.beads" ]; then
            (cd /workspace && bd init 2>/dev/null) || true
            echo "  ✓ Beads initialized"
        fi
    fi

    # 3. Generate aliases from template
    if [ -f /workspace/devpods/templates/turboflow_aliases.sh ]; then
        cp /workspace/devpods/templates/turboflow_aliases.sh "$ALIAS_FILE"
        echo "  ✓ Aliases installed"
    fi

    # If aliases weren't generated by setup.sh, create a minimal set
    if [ ! -f "$ALIAS_FILE" ]; then
        cat > "$ALIAS_FILE" << 'ALIASEOF'
export CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1
alias rf='npx ruflo@latest'
alias rf-doctor='npx ruflo@latest doctor --fix'
alias rf-swarm='npx ruflo@latest swarm init --topology hierarchical --max-agents 8 --strategy specialized'
alias rf-status='npx ruflo@latest status'
alias rf-plugins='npx ruflo@latest plugins list'
alias bd-ready='bd ready'
alias bd-list='bd list'
alias gnx='npx gitnexus'
alias gnx-analyze='npx gitnexus analyze'
turbo-status() {
    echo "TurboFlow 4.0 Status"
    claude --version 2>/dev/null && echo "  ✓ Claude Code" || echo "  ✗ Claude Code"
    npx ruflo@latest --version 2>/dev/null && echo "  ✓ Ruflo" || echo "  ✗ Ruflo"
    command -v dolt &>/dev/null && echo "  ✓ Dolt" || echo "  ✗ Dolt"
    command -v bd &>/dev/null && echo "  ✓ Beads" || echo "  ✗ Beads"
}
ALIASEOF
        echo "  ✓ Minimal aliases created"
    fi

    # Source aliases for this session
    source "$ALIAS_FILE" 2>/dev/null || true

    # Ensure .bashrc sources aliases
    grep -q 'turboflow_aliases' "$HOME/.bashrc" 2>/dev/null || \
        echo '[ -f "$HOME/.turboflow_aliases" ] && source "$HOME/.turboflow_aliases"' >> "$HOME/.bashrc"

    # 4. MCP registration (needs claude to be available)
    if command -v claude &>/dev/null; then
        claude mcp add ruflo -- npx -y ruflo@latest 2>/dev/null || true
        npx gitnexus setup 2>/dev/null || \
            claude mcp add gitnexus -- npx -y gitnexus mcp 2>/dev/null || true
        echo "  ✓ MCP servers registered"
    fi

    # 5. Statusline Pro
    STATUSLINE_SCRIPT="$HOME/.claude/turbo-flow-statusline.sh"
    if [ -f /workspace/devpods/templates/statusline.sh ] && [ ! -f "$STATUSLINE_SCRIPT" ]; then
        mkdir -p "$HOME/.claude" 2>/dev/null || true
        cp /workspace/devpods/templates/statusline.sh "$STATUSLINE_SCRIPT"
        chmod +x "$STATUSLINE_SCRIPT"
        echo "  ✓ Statusline installed"
    fi

    # 6. API key check
    if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
        echo "  ✓ ANTHROPIC_API_KEY is set"
    else
        echo "  ⚠ ANTHROPIC_API_KEY not set — pass via: docker run -e ANTHROPIC_API_KEY=sk-..."
    fi

    touch "$DONE_FLAG"
    echo ""
    echo "  ✓ First boot complete. Run 'turbo-status' to verify."
    echo ""
fi

# ── Hand off to CMD ──────────────────────────────────────────────────────────
exec "$@"
